services:
  admin-api:
    build:
      context: .
      dockerfile: presentation/admin-api/Dockerfile
    container_name: game-admin-api
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - SERVER_PORT=5002
    ports:
      - "5002:5002"
    volumes:
      - maven-repo:/root/.m2/repository
    networks:
      - game-system-network
    restart: unless-stopped

  user-api:
    build:
      context: .
      dockerfile: presentation/user-api/Dockerfile
    container_name: game-user-api
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - SERVER_PORT=5001
    ports:
      - "5001:5001"
    volumes:
      - maven-repo:/root/.m2/repository
    networks:
      - game-system-network
    restart: unless-stopped

volumes:
  maven-repo:

networks:
  game-system-network:
    driver: bridge
