services:
  admin-api:
    build:
      context: ./
      dockerfile: presentation/admin-api/Dockerfile
    container_name: game-system-admin-api
    environment:
      - DATABASE_URL=jdbc:mysql://68.183.177.52:3306/game-development?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=GameHub@2025
      - SERVER_PORT=5001
    ports:
      - "5001:5001"
    networks:
      - game-network
    restart: unless-stopped

  user-api:
    build:
      context: ./
      dockerfile: presentation/user-api/Dockerfile
    container_name: game-system-user-api
    environment:
      - DATABASE_URL=jdbc:mysql://68.183.177.52:3306/game-development?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=GameHub@2025
      - SERVER_PORT=8004
    ports:
      - "8004:8004"
    networks:
      - game-network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: game-redis
    ports:
      - "6379:6379"
    networks:
      - game-network
    restart: unless-stopped

volumes:
  mysql_data:
networks:
  game-network:
    driver: bridge