server:
  port: 5003
spring:
  application:
    name: game-system
  output:
    ansi.enabled: ALWAYS
  datasource:
    url: jdbc:mysql://68.183.177.52:3306/game-development?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: GameHub@2025
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: true
      connection-timeout: 20000
      minimum-idle: 5
      maximum-pool-size: 15
      idle-timeout: 300000
      max-lifetime: 1200000
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true
    show-sql: true
  management:
    endpoint:
      health:
        show-details: always
    endpoints:
      web:
        exposure:
          include: health,info,metrics
  logging:
    level:
      org.springframework:
        security: DEBUG